cergy_category:
    resource: "@CergyCategoryBundle/Controller/"
    type:     annotation
    prefix:   /category

cergy_book:
    resource: "@CergyBookBundle/Controller/"
    type:     annotation
    prefix:   /book

cergy_api_news:
    resource: "@CergyApiBundle/Controller/NewsController.php"
    type:     rest
    prefix:   /api

cergy_api_book:
    resource: "@CergyApiBundle/Controller/BookController.php"
    type:     rest
    prefix:   /api

cergy_users:
    resource: "@CergyUsersBundle/Controller/"
    type:     annotation
    prefix:   /

cergy_news:
    resource: "@CergyNewsBundle/Controller/"
    type:     annotation
    prefix:   /news

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

