Cergy\NewsBundle\Entity\News:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 100
                minMessage: Trop petit
                maxMessage: Trop long {{ limit }}
        content:
            - NotBlank: ~
            - Length:
                min: 3
                max: 500
                minMessage: Trop petit
                maxMessage: Trop long {{ limit }}
            - NotEqualTo:
                value : "test"